@startuml
title Register Chat ID Scenario
actor       TelegramUser as user
participant Bot as bot
participant Hub as hub
database    Database    as db

user -> bot
bot -> hub: Chat ID
hub -> db: Chat ID
@enduml
